---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: List users
      tags:
      - Users
      responses:
        '200':
          description: Users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/User"
                  included:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Attachment"
    post:
      summary: Create user
      tags:
      - Users
      description: Create new user
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/User"
                  included:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Attachment"
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    role:
                      type: string
                      enum:
                      - admin
                      - job_seeker
                      - employer
                    attachments_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          title:
                            type: string
                          file_path:
                            type: string
                            example: https://loremflickr.com/300/300
                          kind:
                            type: string
                            enum:
                            - resume
                            - cover_letter
                            - photo
                  required:
                  - name
                  - email
                  - role
  "/users/{id}":
    get:
      summary: Show user
      tags:
      - Users
      description: Show a user
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/User"
                  included:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Attachment"
        '404':
          description: Not found
    put:
      summary: Update user
      tags:
      - Users
      description: Update a user
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '202':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/User"
                  included:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Attachment"
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    role:
                      type: string
                      enum:
                      - admin
                      - job_seeker
                      - employer
                    attachments_attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                          file_path:
                            type: string
                            example: https://loremflickr.com/300/300
                          kind:
                            type: string
                            enum:
                            - resume
                            - cover_letter
                            - photo
                          _destroy:
                            type: boolean
                  required:
                  - name
                  - email
                  - role
    delete:
      summary: Destroy a user
      tags:
      - Users
      description: Destroy a user
      parameters:
      - name: id
        in: path
        required: true
      responses:
        '204':
          description: Not contet
        '404':
          description: Not found
components:
  schemas:
    Attachment:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          example: attachments
        attributes:
          type: object
          properties:
            title:
              type: string
            kind:
              type: string
              enum:
              - resume
              - cover_letter
              - photo
            file_path:
              type: string
              example: https://loremflickr.com/300/300
    User:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          example: users
        attributes:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              example: email@app.com
            role:
              type: string
              enum:
              - admin
              - job_seeker
              - employer
            attachment_count:
              type: object
              properties:
                resume:
                  type: integer
                cover_letter:
                  type: integer
                photo:
                  type: integer
          required:
          - name
          - email
          - role
        relationships:
          type: object
          properties:
            attachments:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                        example: attachments
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
